artifact_location: file:///e:/plant-disease-classification/notebooks/../ml-runs/0
creation_time: 1686376617831
experiment_id: '0'
last_update_time: 1686376617831
lifecycle_stage: active
name: Default
