name: CML & DVC
on: [push]
jobs:
    train-and-report:
      runs-on: ubuntu-latest    
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
          with:
            python-version: '3.10.11'
      - uses: iterative/setup-cml@v1
      - name: 'Train and Evaluate model'
        shell: bash
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Install requirements
          pip install --upgrade pip
          pip install -r requirements.txt

          # Pull data & run-cache from S3 and reproduce pipeline
          dvc pull --run-cache
          dvc repro

          # Report metrics
          echo "## Metrics" >> report.md
          git fetch --prune
          dvc metrics diff master --show-md >> report.md

